# Generated by Django 3.2 on 2021-05-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='animales'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='lugares'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='noticias'),
        ),
    ]
