# Generated by Django 3.2 on 2021-05-16 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_noticia_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='video',
        ),
    ]
