# Generated by Django 3.2 on 2021-05-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_noticia_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
