# Generated by Django 3.2 on 2021-05-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_noticia_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video_animal'),
        ),
    ]
