# Generated by Django 3.2 on 2021-05-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_animal_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video_lugares'),
        ),
    ]
